### ISSUE TITLE
无法控制生成图片的大小

### ISSUE THREAD

**Issue by alsotang** [zenozeng/node-yaqrcode#1]
希望在生成图片的时候，可以传 `{width: xx, height: yy}` 参数

**Comment by zenozeng** [comment]
可以问一下应用场景吗？我觉得可能这种场合会直接用 <img> 标签加上 css 的 width 和 height 来控制了。

**Comment by zenozeng** [comment]
恩，想了一下确实有必要，我再改下代码好了。

**Comment by alsotang** [comment]
嗯嗯，如果通过 css 控制的话，图片会模糊。我现在直接用 qrcode 在前端生成了。

2015-02-14 11:02 GMT+08:00 Zeno Zeng notifications@github.com:

**Comment by zenozeng** [comment]
用 css 的话，倒是有个 image-rendering 属性可以控制啦。

**Comment by alsotang** [comment]
那还真是个实验属性，在 chrome 中，`crisp-edges` 都不见了

[image: 内嵌图片 1]

2015-02-14 19:41 GMT+08:00 Zeno Zeng <notifications@github.com>:

**Comment by alsotang** [comment]
那还真是个实验属性，在 chrome 中，`crisp-edges` 都不见了

![image](https://cloud.githubusercontent.com/assets/1147375/6199750/5dc82e42-b492-11e4-8f43-ddd3c0f18c28.png)

**Comment by zenozeng** [comment]
恩，工程使用确实目前还不太现实。
