### ISSUE TITLE
Problem creating QR code with longer strings

### ISSUE THREAD

**Issue by jeltok** [zenozeng/node-yaqrcode#2]
It looks like there is a problem with creating QR code with longer strings, e.g.

'bitcoin:55162b4f35dc8fe637372ac1?amount=0.55169320&label=Order#18'

The qrcode function goes into infinite recusrion and overflows the stack.
I think the problem is in how parameters for function gen() are being passed in line 19 of index.js file. I might be mistaken though.

I was able to mitigate the problem by calling the qrcode function with additional parameter:

qrcode(str, {typeNumber:6})

**Comment by zenozeng** [comment]
Seems a bug due to the API change in https://github.com/zenozeng/node-yaqrcode/commit/450a4347ae1c36ad538d43fc4b649226a186be67.

**Comment by zenozeng** [comment]
@jeltok yaqrcode@0.2.0 was published to npm and should work with longer strings by default.

**Comment by jeltok** [comment]
Thanks a lot!
