### ISSUE TITLE
Cannot find module 'qrcode'

### ISSUE THREAD

**Issue by Klemen1337** [zenozeng/node-yaqrcode#3]
Hi,
I got `Cannot find module 'qrcode'`, so I imported it like this `qrcode = require('../../node_modules/yaqrcode/index')` and now it works.

**Comment by kevin-smets** [comment]
Just use `qrcode = require('yaqrcode');`, the docs are a bit off apparently.

**Comment by kevin-smets** [comment]
This is not fixed? Why close it? I'm sure others will encounter it.

**Comment by zenozeng** [comment]
@Klemen1337 @kevin-smets Sorry for the typo in usage section and my late response. Fixed in https://github.com/zenozeng/node-yaqrcode/commit/e5e423f14dacea0c748a8414219cc52cefc8397d.
